export const data = {
  products: [
    {
      id: 1,
      name: 'Slim Shirt',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
      countInStock: 0,
    },
    {
      id: 2,
      name: 'long Shirt',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
      countInStock: 1,
    },
    {
      id: 3,
      name: 'Best Shirt',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
      countInStock: 21,
    },
    {
      id: 4,
      name: 'Extra L Shirt',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
      countInStock: 211,
    },
    {
      id: 5,
      name: 'Slim Pants',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 102,
    },
    {
      id: 6,
      name: 'Best fit Pants',
      image: 'images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 129,
    },
    {
      id: 7,
      name: 'Slim shorts',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
      countInStock: 20,
    },
    {
      id: 8,
      name: 'Slim Shoes',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
      countInStock: 27,
    },
    {
      id: 9,
      name: 'Slim Loafers',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
      countInStock: 21,
    },
    {
      id: 10,
      name: 'Slim Shirt',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
    },
    {
      id: 11,
      name: 'Slim Shirt',
      image: '/images/d1.jpg',
      brand: 'Nike',
      price: 60,
      rating: 4.5,
      numReviews: 12,
    },
  ],
};
